version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: umls
      MYSQL_USER: root
      MYSQL_PASSWORD: pass

  ctakes_webserver:
    build: .
    environment:
      VIRTUAL_HOST: ctakes_webserver
      VIRTUAL_PORT: 8081
      JDBC_URL: jdbc:mysql://db:3306/umls?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: root
      JDBC_PASS: pass
    restart: always
    ports:
      - "8091:8081"
    volumes:
      - "./tomcat/webapps:/usr/local/tomcat/webapps"
    links:
      - db

volumes:
  db_data:
